<?php 
$fId  		= Mage::registry('efatt-invoice-id');
$lUrl 		= "*/sales_invoice/viewinvoicespage/invoice_id/" . $fId; 
$mUrl 		= Mage::helper('adminhtml')->getUrl($lUrl);
$fKey 		= Mage::getSingleton('core/session')->getFormKey(); 
$config   	= Mage::registry('efatt-config'); 
$cc   		= Mage::registry('efatt-cessionario-committente');
$currencies = Mage::registry('efatt-currencies');
$countryList = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false);
$fJsonUrl	= Mage::getBaseUrl('js') . "/efatt/fatturaPA_1.2_schema.json";
$fXmlUrl	= Mage::getBaseUrl('js') . "/efatt/fatturaPA_1.2.hbs";

$json = file_get_contents($fJsonUrl);
$jsonDecoded = json_decode($json);
$json = $jsonDecoded;
?>

<div id="page:main-container">

<form method="post" action='<?php echo $mUrl; ?>'>

<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head head-sales-invoice"><?php echo "Fattura " . $fId ?> </h3></td>
            <td class="form-buttons"><button  type="submit" class="scalable save" style=""><span><span><span>Genera Fattura Elettronica</span></span></span></button></td>
        </tr>
    </tbody></table>
</div>


<input name="form_key" type="hidden" value='<?php echo $fKey ?>' />

<div class="box">

<!--
<div class="entry-edit">
<div class="entry-edit-head collapseable">
<strong>Fattura Elettronica</strong>
</div>
<div class="fieldset">
<table cellspacing="0" class="form-list">
<tbody>
-->

<?php
function printInput($type, $title, $node, $k, $mandatory) {

        if($title == "") $title = $k;

        if($mandatory == "Y") {
            $border = " style='border-color: red;' ";
        } else {
            $border = "";
        }

        echo '<label>' . $title . '</label><br>';
        echo "<input " . $border . " type='text' :value='" . $node . "'><br>";
    
}

function printPanel($title, $k) {
    $panelTitle = $k;
    echo '<h2><strong>' . $title . '</strong></h2>';
}

function parseChildren($el, $n, $mandatory = "") {

    foreach ($el as $k => $v) {
        $n .= "." . $k;

        if($k == "properties") $mandatory = "Y";

        if($k == "additionalProperties") $mandatory = "N";

        $type   = $v->type;
        $title  = $v->title;
        //echo $n . " - " . $type . "<br>";
        if($type == "object") printPanel($title, $k);

        if(isset($type) && $type != "object") {
            printInput($type, $title, $node, $k, $mandatory);
        }
        parseChildren($v, $k, $mandatory);
    }

}

parseChildren($json, "");

/*
foreach ($json as $k => $v) {

    parseChildren($v, $k);
}
*/

?>

<!-- end page -->    
</div>

</form>
</div>


<script type="text/javascript">// <![CDATA[

/*
Calendar.setup({
    inputField : 'DatiGenerali_DatiGeneraliDocumento_Data',
    ifFormat : '%Y-%m-%e',
    button : 'date_from_trig',
    align : 'Bl',
    singleClick : true
});

*/
// ]]></script>

  
