<?php 
$fId  		= Mage::registry('efatt-invoice-id');
$lUrl 		= "*/sales_invoice/viewinvoicespage/invoice_id/" . $fId; 
$mUrl 		= Mage::helper('adminhtml')->getUrl($lUrl);
$fKey 		= Mage::getSingleton('core/session')->getFormKey(); 
$config   	= Mage::registry('efatt-config'); 
$cc   		= Mage::registry('efatt-cessionario-committente');
?>

<div id="page:main-container">

<form method="post" action='<?php echo $mUrl; ?>'>

<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head head-sales-invoice"><?php echo "Fattura " . $fId ?> </h3></td>
            <td class="form-buttons"><button  type="submit" class="scalable save" style=""><span><span><span>Genera Fattura Elettronica</span></span></span></button></td>
        </tr>
    </tbody></table>
</div>


<input name="form_key" type="hidden" value='<?php echo $fKey ?>' />

<div class="box">
    <!--Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Dati Trasmissione</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label>Id paese</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_IdTrasmittente_IdPaese"></td>
            </tr>
            <tr>
                <td class="label"><label>Id codice</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_IdTrasmittente_IdCodice"></td>
            </tr>
            <tr>
                <td class="label"><label>Progressivo Invio</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_ProgressivoInvio"></td>
            </tr>
            <tr>
                <td class="label"><label>Formato Trasmissione</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_FormatoTrasmissione"></td>
            </tr>
            <tr>
                <td class="label"><label>Codice Destinatario</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_CodiceDestinatario"></td>
            </tr>
            </tbody></table>
        </div>
    </div>

    <!-- cedente prestatore from config -->
    <?php foreach ($config as $key => $fields) { ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong><?php echo $key?></strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody>
			<?php foreach ($fields as $field => $value) { ?>
			<tr>
                <td class="label"><label><?php echo $field ?></label></td>
                <td class="value"><input type="text" name="<?php echo $key . '_' . $field ?>" value="<?php echo $value ?>"></td>
            </tr>
			<?php } ?>
	</tbody></table>
        </div>
    </div>
	<?php } ?>


    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Cessionario Committente - Dati Anagrafici - Id Fiscale IVA</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody><tr>
                <td class="label"><label>Id Paese</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_DatiAnagrafici_IdFiscaleIVA_IdPaese"></td>
            </tr>
            <tr>
                <td class="label"><label>Id Codice</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_DatiAnagrafici_IdFiscaleIVA_IdCodice"></td>
            </tr>
            </tbody></table>
        </div>
    </div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Cessionario Committente - Dati Anagrafici - Anagrafica</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody><tr>
                <td class="label"><label>Denominazione</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_DatiAnagrafici_Anagrafica_Denominazione" value="<?php echo $cc['company'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Nome</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_DatiAnagrafici_Anagrafica_Nome" value="<?php echo $cc['firstname'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Cognome</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_DatiAnagrafici_Anagrafica_Cognome" value="<?php echo $cc['lastname'] ?>"></td>
            </tr>
            </tbody></table>
        </div>
    </div>

        <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Cessionario Committente - Sede</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody><tr>
                <td class="label"><label>Indirizzo</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_Sede_Indirizzo" value="<?php echo $cc['street'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>CAP</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_Sede_CAP" value="<?php echo $cc['postcode'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Comune</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_Sede_Comune" value="<?php echo $cc['city'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Nazione</label></td>
                <td class="value"><input type="text" name="CessionarioCommittente_Sede_Nazione" value="<?php echo $cc['country_id'] ?>"></td>
            </tr>
            </tbody></table>
        </div>
    </div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Dati Generali - Dati Generali Documento</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody><tr>
                <td class="label"><label>Tipo Documento</label></td>
                <td class="value"><input type="text" name="DatiGenerali_DatiGeneraliDocumento_TipoDocumento">
				<p class="note">tipologia del documento oggetto della trasmissione (fattura, acconto/anticipo su fattura, nota di credito, parcella …).</p>
                </td>
            </tr>
            <tr>
                <td class="label"><label>Divisa</label></td>
                <td class="value">
                <select name="DatiGenerali_DatiGeneraliDocumento_Divisa">
					<option value="USD">United States Dollars</option>
					<option value="EUR" selected="selected">Euro</option>
					<option value="GBP">United Kingdom Pounds</option>
					<option value="DZD">Algeria Dinars</option>
					<option value="ARP">Argentina Pesos</option>
					<option value="AUD">Australia Dollars</option>
					<option value="ATS">Austria Schillings</option>
					<option value="BSD">Bahamas Dollars</option>
					<option value="BBD">Barbados Dollars</option>
					<option value="BEF">Belgium Francs</option>
					<option value="BMD">Bermuda Dollars</option>
					<option value="BRR">Brazil Real</option>
					<option value="BGL">Bulgaria Lev</option>
					<option value="CAD">Canada Dollars</option>
					<option value="CLP">Chile Pesos</option>
					<option value="CNY">China Yuan Renmimbi</option>
					<option value="CYP">Cyprus Pounds</option>
					<option value="CSK">Czech Republic Koruna</option>
					<option value="DKK">Denmark Kroner</option>
					<option value="NLG">Dutch Guilders</option>
					<option value="XCD">Eastern Caribbean Dollars</option>
					<option value="EGP">Egypt Pounds</option>
					<option value="FJD">Fiji Dollars</option>
					<option value="FIM">Finland Markka</option>
					<option value="FRF">France Francs</option>
					<option value="DEM">Germany Deutsche Marks</option>
					<option value="XAU">Gold Ounces</option>
					<option value="GRD">Greece Drachmas</option>
					<option value="HKD">Hong Kong Dollars</option>
					<option value="HUF">Hungary Forint</option>
					<option value="ISK">Iceland Krona</option>
					<option value="INR">India Rupees</option>
					<option value="IDR">Indonesia Rupiah</option>
					<option value="IEP">Ireland Punt</option>
					<option value="ILS">Israel New Shekels</option>
					<option value="ITL">Italy Lira</option>
					<option value="JMD">Jamaica Dollars</option>
					<option value="JPY">Japan Yen</option>
					<option value="JOD">Jordan Dinar</option>
					<option value="KRW">Korea (South) Won</option>
					<option value="LBP">Lebanon Pounds</option>
					<option value="LUF">Luxembourg Francs</option>
					<option value="MYR">Malaysia Ringgit</option>
					<option value="MXP">Mexico Pesos</option>
					<option value="NLG">Netherlands Guilders</option>
					<option value="NZD">New Zealand Dollars</option>
					<option value="NOK">Norway Kroner</option>
					<option value="PKR">Pakistan Rupees</option>
					<option value="XPD">Palladium Ounces</option>
					<option value="PHP">Philippines Pesos</option>
					<option value="XPT">Platinum Ounces</option>
					<option value="PLZ">Poland Zloty</option>
					<option value="PTE">Portugal Escudo</option>
					<option value="ROL">Romania Leu</option>
					<option value="RUR">Russia Rubles</option>
					<option value="SAR">Saudi Arabia Riyal</option>
					<option value="XAG">Silver Ounces</option>
					<option value="SGD">Singapore Dollars</option>
					<option value="SKK">Slovakia Koruna</option>
					<option value="ZAR">South Africa Rand</option>
					<option value="KRW">South Korea Won</option>
					<option value="ESP">Spain Pesetas</option>
					<option value="XDR">Special Drawing Right (IMF)</option>
					<option value="SDD">Sudan Dinar</option>
					<option value="SEK">Sweden Krona</option>
					<option value="CHF">Switzerland Francs</option>
					<option value="TWD">Taiwan Dollars</option>
					<option value="THB">Thailand Baht</option>
					<option value="TTD">Trinidad and Tobago Dollars</option>
					<option value="TRL">Turkey Lira</option>
					<option value="VEB">Venezuela Bolivar</option>
					<option value="ZMK">Zambia Kwacha</option>
					<option value="EUR">Euro</option>
					<option value="XCD">Eastern Caribbean Dollars</option>
					<option value="XDR">Special Drawing Right (IMF)</option>
					<option value="XAG">Silver Ounces</option>
					<option value="XAU">Gold Ounces</option>
					<option value="XPD">Palladium Ounces</option>
					<option value="XPT">Platinum Ounces</option>
				</select>
            </tr>
            <tr>
                <td class="label"><label>Data</label></td>
                <td class="value"><input type="text" name="DatiGenerali_DatiGeneraliDocumento_Data"></td>
            </tr>
            <tr>
                <td class="label"><label>Numero</label></td>
                <td class="value"><input type="text" name="DatiGenerali_DatiGeneraliDocumento_Numero"></td>
            </tr>
            </tbody></table>
        </div>
    </div>



<!-- end page -->    
</div>

</form>
</div>

