<?php 
$fId  		= Mage::registry('efatt-invoice-id');
$lUrl 		= "*/sales_invoice/viewinvoicespage/invoice_id/" . $fId; 
$mUrl 		= Mage::helper('adminhtml')->getUrl($lUrl);
$fKey 		= Mage::getSingleton('core/session')->getFormKey(); 
$config   	= Mage::registry('efatt-config'); 
$cc   		= Mage::registry('efatt-cessionario-committente');
?>

<pre>
<?php var_dump($config); ?>
</pre>

<div id="page:main-container">

<form method="post" action='<?php echo $mUrl; ?>'>

<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head head-sales-invoice"><?php echo "Fattura " . $fId ?> </h3></td>
            <td class="form-buttons"><button  type="submit" class="scalable save" style=""><span><span><span>Genera Fattura Elettronica</span></span></span></button></td>
        </tr>
    </tbody></table>
</div>


<input name="form_key" type="hidden" value='<?php echo $fKey ?>' />

<div class="box">
    <!--Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Dati Trasmissione</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label>Id paese</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_IdTrasmittente_IdPaese"></td>
            </tr>
            <tr>
                <td class="label"><label>Id codice</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_IdTrasmittente_IdCodice"></td>
            </tr>
            <tr>
                <td class="label"><label>Progressivo Invio</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_ProgressivoInvio"></td>
            </tr>
            <tr>
                <td class="label"><label>Formato Trasmissione</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_FormatoTrasmissione"></td>
            </tr>
            <tr>
                <td class="label"><label>Codice Destinatario</label></td>
                <td class="value"><input type="text" name="DatiTrasmissione_CodiceDestinatario"></td>
            </tr>
            </tbody></table>
        </div>
    </div>

    <!--Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <strong>Cessionario Committente</strong>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody><tr>
                <td class="label"><label>Codice Fiscale</label></td>
                <td class="value"><input type="text" name="cessionario_committente_codice_fiscale" value="<?php echo $cc['vat_id'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Denominazione</label></td>
                <td class="value"><input type="text" name="cessionario_committente_denominazione" value="<?php echo $cc['company'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Indirizzo</label></td>
                <td class="value"><input type="text" name="cessionario_committente_indirizzo" value="<?php echo $cc['street'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>CAP</label></td>
                <td class="value"><input type="text" name="cessionario_committente_cap" value="<?php echo $cc['postcode'] ?>"></td>
            </tr>
            <tr>
                <td class="label"><label>Comune</label></td>
                <td class="value"><input type="text" name="cessionario_committente_comune" value="<?php echo $cc['city'] ?>" ></td>
            </tr>
            <tr>
                <td class="label"><label>Provincia</label></td>
                <td class="value"><input type="text" name="cessionario_committente_provincia" value="<?php echo $cc['region'] ?>" ></td>
            </tr>
            <tr>
                <td class="label"><label>Nazione</label></td>
                <td class="value"><input type="text" name="cessionario_committente_nazione" value="<?php echo $cc['country_id'] ?>"></td>
            </tr>
            </tbody></table>
        </div>
    </div>
</div>

</form>
</div>

